.gitattributes

Resolve #5.
However there is some codes causing linguist to still think is C++. Eventually we will have the functions reformat to meet our requirement to work with Cxbx-Reloaded. At this state, it is shown as main C.

Fix GitHub linguist detection

---

OOVPA.h
XbSymbolDatabase.h

Enum is default to int, in C we can't force it to use different size. Type-cast is a requirement.
I already have a part 2 fix for remaining warnings. However, it is conflict with PR #12.
This resolve partial warning issues for issue #7.
It can be safely merge into master.

Fix warnings part 1

---

OOVPA.h

It works as intended plus flexible array member is supported since C99 standard.
The warning from Visual Studio is `C4200: nonstandard extension used: zero-sized array in struct/union`.

Ignore warning for nonstandard extension from Visual Studio

---

XbSymbolDatabase.c
XbSymbolDatabase.vcxproj.filters
xbSymbolDatabase.vcxproj

This pull request contain...
* Treat warnings as errors. (since there are absolutely no warning anymore)
* Check xbe header for library section contain DSOUND string before enforce scan for DSOUND symbols from known 4039 missing library version data.
* Replace goto to "do while" statement.
* Fix coding to our standard formatting by hand.
* Remove some extra checking in if statements.
* Ignore certain spots in D3D checking if below 3911 when supposed to.
* We don't support any unofficial titles under revision 3911 builds in HLE.

More updates

---

XbSymbolDatabase.c

I came up with a solution to auto-detect and fix an incorrect detection of EmuD3DDeferredRenderState within Cxbx-Reloaded, however, it requires that the offset of the derived D3DRS_CULLMODE symbol is passed to the emulator.
This PR makes that happen.
The Cxbx-R side will be pushed shortly: Just note that Cxbx-R uses this information to automatically correct a broken EmuD3DDeferredRenderState, as well as show a notification to submit an issue to fix it upstream in XbSymbolDatabase: This is beneficial for everyone.

Register D3DRS_CullMode

---

XbSymbolDatabase.c
XbSymbolDatabase.h

- Fix case-sensitive include-path: Unlike Windows, some platforms are case-sensitive. So the include path must be written properly
- Fix use of the `inline` keyword: The inline keyword has a different meaning in different versions of C. I turned the functions which are only in one compilation unit into `static inline`. The function which isn't accessible from elsewhere isn't `inline` anymore.
The code is untested, because there's many other issues in the codebase, and I don't have 32 bit compatibility to test XbSymbolDatabase at all (See issue 25 about x64 support).

Cleanup for non-Windows platfoms and non-MSVC compilers

---

Xbe.h

A first step towards #25.
This will require "stdint.h" (C99+).
I did not want to mess with `char` types. We should have a static assert for those.
The code is untested, because there's many other issues in the codebase, and I don't have 32 bit compatibility to test XbSymbolDatabase at all. I did not even confirm correctness of the Xbe.h struct layouts on their own.

Use fixed-size types in Xbe.h

---

XbSymbolDatabase.c
XbSymbolDatabase.h

Finally, 64-bit program and no restriction on memory range are supported.
using XbSymbolScan function is deprecated. Recommendation are:
* XbSymbolScanFileImage (full file image scan purpose)
* XbSymbolScanRunTime (scan runtime xbe by an emulator or the like)
resolve #25
P.S. Any extended concern or found something off (anything really). Feel free to comment below.

Support 64-bit program and outside hardcode xbox base memory range

---

CMakeLists.txt

By include CMakeLists.txt file, any third-party using CMake can directly include this file without a hassle.
(Part of a requirement for XbSymbolCacheGenTest project.)

Generic CMake support

---

XbSymbolDatabase.c
XbSymbolDatabase.h

More or less a copy and paste from Cxbx-Reloaded's checking for any duplicated OOVPAs and "expanded?" errors. Which also include modification from C++ codes to C. And include error counts for `XbSymbolDataBaseTestOOVPAs` function.
Currently, there are total of 36 errors for D3DDevice_xxxxx symbols.
We also need to include support for verifying different symbol matching same address as well. TBA
NOTE: There may be a chance of add parameter support later on down the path for different test and so on. In theory, it may will be a separate function.

Internal Debug Support

---

CMakeLists.txt
xbSymbolDatabase.vcxproj

Since library by itself will not compile unless delcared in other project.
Quick hotfix.

Add _CRT_SECURE_NO_WARNINGS to project

---

XbSymbolDatabase.c

This should affect GCC, and probably also Clang (not sure if the preprocessor checks are good).
Commits are self-explanatory:
- `_BitScanReverse` does not exist in the GCC world. The zero-case is never encountered, but I added it for completeness; it returns 32 (which means the first set bit is not within the lower 32 bits).
- `strncat` with `n == sizeof(src)` gives a warning (as zero included - it was still initialized and appended though). There's no good reason to use `strncat` as `strcat` behaves the same. The `strncat` using `OOVPA_TABLE_COUNT` was even worse, as there's no reason this should be done; its only job was a cryptic form of `strlen("string") + 1`.
**Please confirm I did not break Windows support.**
Ideally someone would also test on macOS or using another clang …

Fix GNU compiler support

---

XbSymbolDatabase.c
XbSymbolDatabase.h

Added:
* XbSymbolBypassBuildVersionLimit to API usage. (See API for details.)
* Is a requirement in order to perform a depth testing internally.
* XbSymbolSetOutputVerbosity to API usage. (See API for details.)
* By include this function, the process will run faster internal by skip certain verbose message with string formats provided.
* XbSymbolOutputMessageFormat to reduce unnecessary buffer size holder in any functions.
* Output debug message of what library and section are being scanned.
* **NEW** XbSymbolContinuousSigScan to API usage. (See API for details.)
* Is a requirement in order to perform a depth testing internally.
* **NEW** XbSymbolFirstDetectAddressOnly to API usage. (See API for details.)
* Is a requirement in order to perform a depth testing internally.

Some Debug Updates

---

OOVPA.h
OOVPADatabase/D3D8LTCG_OOVPA.inl
OOVPADatabase/D3D8_OOVPA.inl
OOVPADatabase/DSound_OOVPA.inl
OOVPADatabase/XActEng_OOVPA.inl
OOVPADatabase/XGraphic_OOVPA.inl
OOVPADatabase/XNet_OOVPA.inl
OOVPADatabase/XOnline_OOVPA.inl
OOVPADatabase/Xapi_OOVPA.inl
XbSymbolDatabase.c

* Fixed OV_BYTE bug since only value is acceptable for 1 byte size.
* However, current codebase isn't using the OV_ENTRY macro.
* Current codebase will eventually replace default OV entries to macro usage.
* Rename OOVPA_TABLE_COUNT to XBSDB_ARRAY_SIZE
Plus a new macro, **OV_MATCH**, for ability to insert multiple values in one line instead of multiple lines.
Image proof of above image expands to:

Minor improvement

---

XbSymbolDatabase.c

* nxdk declares `wchar_t` in stddef, so we need to include it.
* Fixes a bug (with warning) introduced in #54 where https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanreverse-bitscanreverse64?view=vs-2019 takes `unsigned long` pointer as first argument.

Fix NXDK support

---

XbSymbolDatabase.c

Title says it all.
Apparently this bug has exist since the introduction of `XbSymbolRegisterLibrary` API. `g_library_flag` was used in `XbSymbolSectionScan` until it was disabled due to not being functional ever since.

Fix Specific Library Scan in XbSymbolScan API

---

OOVPADatabase/JVS/4831.inl
OOVPADatabase/JVS_OOVPA.inl
OOVPADatabase/Xapi_OOVPA.inl
XbSymbolDatabase.c
XbSymbolDatabase.h

Separate JVS symbols from XAPI library into its own library. Plus nothing had been changed in OOVPAs except for replace default array to OV_MATCH macro.
The documentation in JVS notes are used by @LukeUsher record:

Relocate JVS into Separate Section

---

XbSymbolDatabase.c

Apparently, I had overlooked `OOVPAErrorString` function already has `SymbolDatabaseList *data` with given index for able get library flag, function name, *and version* too. I also removed BuildVersion parameter passdown as well as it is not necessary.
Functional example:
Before: **(wrong)**
```
ERROR  : OOVPATable  1 4039 [  27] D3DDevice_BeginPush, comparing against OOVPATable  2 4039 [ 412] D3DDevice_BeginPush2 : OOVPA's are expanded (left +2, right +2)
ERROR  : OOVPATable  1 4531 [  30] D3DDevice_BeginPush2, comparing against OOVPATable  2 4531 [ 409] D3DDevice_BeginPush : OOVPA's are expanded (left +2, right +2)
```
After: **(correct)**
```
ERROR  : OOVPATable  1 4531 [  27] D3DDevice_BeginPush, comparing against OOVPATable  2 4039 [ 412] D3DDevice_BeginPush2 : OOVPA's are expanded …
```

Fix OOVPA Error String Format

---

OOVPA.h
OOVPADatabase/D3D8/3911.inl
OOVPADatabase/DSound/3911.inl
XbSymbolDatabase.c

With specific detected selection scan for OOVPA, it is become possible to have 2+ identical OOVPAs with a different symbol name.
Using this method will also reduce false warnings and errors as well.

Implement Specific Detected Selection Scan for OOVPA

---

OOVPADatabase/D3D8/3911.inl
OOVPADatabase/D3D8_OOVPA.inl

This pattern works for all known XDK versions, from 3911-5933
Fix #82

Add symbol for D3D_DestroyResource

---

OOVPADatabase/XNet_OOVPA.inl
OOVPADatabase/XOnline_OOVPA.inl
XbSymbolDatabase.c

* migrate xonlines to xonline filter list
* migrate xnet(s|n) and xonline(s) to xnet filter list
* removed XNET symbols from XONLINE list
Tested with Xbox Live xbe file which has XONLINES library, contain XONLINE and XNET sections, with no issues.
With a bonus, the errors has been reduce from 522 to 154.

Merge XONLINE and XNET into Two Databases

---

CMakeLists.txt
XbSymbolDatabase.c
XbSymbolDatabase.h

Design API v3.0
Closes #10
New features: (see XbSymbolDatabase.h file for functions' details)
* XbSymbolDatabase_GenerateLibraryFilter
* XbSymbolDatabase_GenerateSectionFilter
* XbSymbolDatabase_CreateXbSymbolContext
* XbSymbolContext_ScanLibrary (design for multi-thread safe support)
* If there is a dependency on another library's symbols. Such as XACTENG library do depend on DSOUND's symbols. Then second or later libraries will not perform the scan until the library is done scanning in the active thread.
* XbSymbolContext_ScanAllLibraryFilter (design for single-threading only)
* May will change to support multi-thread usage internally.
* XbSymbolContext_RegisterXRefs (currently is a stub function)
* Can be resolved by #39
* XbSymbolContext_Release
Currently, the design is backward …

Design API v3

---

XbSymbolDatabase.c

Recently discovered not all compilers support C11's thread support. Although, only needed mutex support.

HOTFIX: Fix Unix Builds

---

OOVPA.h
OOVPADatabase/D3D8/3911.inl
OOVPADatabase/D3D8LTCG/4627.inl
OOVPADatabase/D3D8LTCG_OOVPA.inl
OOVPADatabase/D3D8_OOVPA.inl
XbSymbolDatabase.h

Close #85
OOVPA changelog:
Removed:
- D3DDevice_SetRenderStateNotInline (1024, was in 4627)
Added:
- D3DDevice_SetRenderStateNotInline (3911)
- Can be detected in LTCG titles
- D3DDevice_SetRenderState (3911)
- D3DDevice_SetRenderState2 (3911)
- Confirmed duplicate functions found in some titles.
Plus added detect macro to able use with xref.
Tested with custom Cxbx-Reloaded from verify symbol cache file with no issue.

Add 2 D3D8 Signatures

---

OOVPADatabase/DSound_OOVPA.inl
XbSymbolDatabase.c

Close #88 
Xbox Live now does register missing references using Cxbx-Reloaded's custom develop build link to this pull request.
2nd commit is a discovery which were preventing DSound's 2nd (actual) OOVPA database to scan.

Fix DSound VTable Not Found

---

XbSymbolDatabase.c

Introduce and use SetXRefDataBase. This fixes incorrect UnResolvedXRefs counting.
Also corrected a comment typo.
This function does individual registration of derived XRef's that are useful but not yet registered.
Called after entire scan.

XRef related code cleanup and fixup

---

CMakeLists.txt
XbSymbolDatabase.c
XbSymbolDatabase.h

These commits fix some build issues Matt and me encountered when building XbSymbolDatabase on Linux (Arch in my case, and Ubuntu I assume for Matt's). These are just to make the code build correctly, I plan to upstream Matt's cli tool and addition XONLINE signatures soon.

Build fixes

---

XbSymbolDatabase.c

This bug was introduced in original pull request #94.
With this fix, I can receive warnings for any signatures that are too high which may or may not need to be lower.

HOTFIX: Corrected bypass build version limit to allow set before start scan

---

.github/workflows/ci.yml

After merge from pull request #111, I notice jobs aren't clarified.
I updated the jobs name to have prefix of "\<platform\> (\<arch\>, \<configuration\>)"

Fix CI Job Names

---

src/OOVPADatabase/D3D8LTCG/3911.inl
src/OOVPADatabase/D3D8LTCG/4039.inl
src/OOVPADatabase/D3D8LTCG_OOVPA.inl

Practically enables rendering in xdk-3911 LTCG games, in this case NASCAR Heat 2002.
Marking as draft in case I find more required patches tomorrow or on Friday, but if I don't I'll just mark it as complete.

Add a signature for D3DDevice_DrawIndexedVertices for xdk-3911 LTCG

---

src/OOVPADatabase/DSound/3911.inl
src/OOVPADatabase/DSound/3936.inl
src/OOVPADatabase/DSound/4242.inl
src/OOVPADatabase/DSound/4627.inl
src/OOVPADatabase/DSound/5344.inl
src/OOVPADatabase/DSound_OOVPA.inl

Resolves 4 errors found from internal test. Plus a duplicate warning detected by update and remove unnecessary extra signature. Plus add The Hulk note to the list.
Total internal test errors before was 154, now it is 150.

Fix couple errors and warnings from DSound OOVPA signatures

---

include/Xbe.h
src/lib/libXbSymbolDatabase.c

Simple test case is NFL Blitz 2002 title which has kernel thunk table within **.idata** section. It is not on the filter list, therefore require to enforce add section outside of filter list.
Plus add chance to avoid false positive if section doesn't have preload flag just in case. And also used for optimization too.

Fix Kernel Thunk Table Not Being Found Outside of Section Filter List

---

src/lib/libXbSymbolDatabase.c

I already verified titles with 4039 and 4134 build. CDirectSoundStream_GetStatus's function of 4039 and below only use one flag which check if CMcpxStream class is ready for input stream packets. 4134 function and later use extended feature of general status.
Low risk merge since I will make a new pull request to Cxbx-Reloaded for resolve GetStatus difference between two different revisions.

DSound: Split CDirectSoundStream_GetStatus into Two Symbols for Difference Handler

---

include/libXbSymbolDatabase.h
src/OOVPADatabase/XOnline/4831.inl
src/OOVPADatabase/XOnline/5233.inl
src/OOVPADatabase/XOnline/5849.inl
src/OOVPADatabase/XOnline_OOVPA.inl

This picks @LukeUsher's Insignia RE wishlist from #74 and adds signatures for them, namely `XOnlineMatchSearch`, `XOnlineMatchSearchResultsLen`, `XOnlineMatchSearchGetResults`, `XOnlineMatchSessionUpdate` and `XOnlineMatchSessionCreate`.
I was only able to check against games built with XDK version 4831, 4928, 5659 and 5849. Testing the versions in-between would be appreciated.

Add some XONLINE signatures

---

CMakeLists.txt
projects/CMakeLists.txt
projects/cli/CMakeLists.txt
src/cli/main.c

This adds a cli tool, which can be used to run symbol detection on an XBE. The actual tool was written by @mborgerson, I only tweaked the CMakeLists to fix building under some Linux distributions and to make building the tool optional (as Cxbx-Reloaded probably doesn't want it built). The Actions file is also his work, I slightly modified it to ignore the readme (like the current Actions file does) and make it use checkout@v2.
The Actions file also uploads the created CLI tool binaries as an artifact. This is then used in @mborgerson's Ghidra XBE plugin, where this artifact is downloaded and included to provide symbol detection.

Add a CLI tool and build it with GH actions

---

.github/workflows/ci.yml

Release Features:
- Monthly release system schedule at 01:01 UTC on the 7th of every month.
- **(Please do not change above to different schedule.)**
- Ability to push tag bump to make a release manually.
- Perform manual run workflow dispatch for early release when necessary.
- **If attempt to re-run workflow dispatch or run new one which repository already have release tag. Then it will not build nor generate another release.**
resolve #112
---
I had personally tested my own custom semantic version's action in the past. The only setback was setting up workflow's side. Now it is resolved and tested from a "TestStuff" repo, if you know where to find it. 😉

Add Release System

---

include/libXbSymbolDatabase.h
src/OOVPADatabase/Xapi/3911.inl
src/OOVPADatabase/Xapi/4242.inl
src/OOVPADatabase/Xapi/5233.inl
src/OOVPADatabase/Xapi_OOVPA.inl

This function is necessary to emulate memory units in Cxbx-Reloaded.
I only checked with XDK 3944 and 4831, so testing with other versions would be appreciated.
EDIT: this now also adds `MU_Init`, which is necessary to derive the memory unit device type. It was tested with xdk versions 3911, 4627, 4831 and 5849.

Added XUnmountMU and MU_Init

---

.github/workflows/pull-request.yml
src/OOVPADatabase/D3D8LTCG/5849.inl

Somehow, #135 changes escaped from clang format lint check from our pull request manager workflow. This pull request resolve the lint verification.
And add a fix for the checkout process to pull merged commit to verify pull request's changes.

fix clang format lint

---

src/cli/main.c

While testing with Ghidra-Xbe extension with Ghrida. I notice couple symbols were not output, including #139 pull request.
This pull request now do manual output derived references that is not part of OOVPA signature database after second part of the scan process.

Fix CLI Tool missing XbSymbolContext_RegisterXRefs call

---

include/libXbSymbolDatabase.h
src/lib/internal_functions.h
src/lib/libXbSymbolDatabase.c

This enables detection of XOnline symbols when the `XONLINLS` library is found. I don't know how exactly it differs from `XONLINES`, but the current signatures seem to be enough for symbol detection to work. The library version seems to always be `5849`, and it can be found in games such as `TOCA Race Driver 2`, `Trivial Pursuit` and `RalliSport Challenge 2`.

Enable XOnline symbol detection when XONLINLS library is found

---

src/OOVPADatabase/XOnline/4721.inl
src/OOVPADatabase/XOnline_OOVPA.inl

This moves the `XOnline` signatures from XDK version 4831 to 4721, allowing `XOnline` symbol detection to work with the Re-Volt Xbox Live Beta.

XOnline: Move 4831 signatures to 4721

---

include/libXbSymbolDatabase.h
projects/cli/CMakeLists.txt
src/lib/internal_functions.h
src/lib/libXbSymbolDatabase.c
src/test/main.cpp

External projects planned to use multi-threading with `XbSymbolContext_ScanLibrary` API is require to provide mutex (un)lock functions and opaque pointer. As they are responsible to create threads and handle requested (un)locks.
This pull request also contain:
- Few fixes to XML doc on APIs.
- Fixed missing additional lock when double unlocks occurred unexpectedly.
This is a temporary workaround fix at the moment until more suitable APIs are provided to priority which library should be scan first and last.

Implement Multi-Threading's Mutex Callback APIs

---

src/test/main.cpp

This bug was outstanding hidden from plain view for long time. With this fix, the errors of mismatch should now correctly output and do not hide even size errors not being output.

HOTFIX: Fix inaccurate symbols comparison error and migrate equal function check

---

include/libXbSymbolDatabase.h
src/lib/internal_functions.h
src/lib/libXbSymbolDatabase.c
src/test/main.cpp

With Dependency API feature, there is no more of random occur failures for any partial library's symbols. Dependency API is require for using `XbSymbolContext_ScanLibrary` API.
I am requesting reviews on the API naming or even discovery of faulty code.
I have personally tested this new change on single thread and multi-threads and confirm random failures of missing symbols has stopped except for one weird bug not relative to this pull request.
Weird bug report is: (fixed in commit 3eb125546e9d7c195aef690b1d96a7258fddd22e)
`ERROR  : g_SymbolAddresses(Raw) is missing UNKNOWN (b0000) 0x00000000 ->`
fixed #168

Implement Dependency API (removed Mutex callback API)

---

.github/workflows/ci.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

With these changes and a fix in [Semantic Version Action](https://github.com/RadWolfie/Semantic-Version-Action). The only warning left is:
```
Annotations
1 warning
GitHub CI: .github#L1
macOS-latest pipelines will use macOS-12 soon. ...
```
However, we are using macOS-latest, currently is macOS-11, at this time which doesn't need any fix.

Bump Github Actions

---

src/test/main.cpp

Issue was found when testing with "NASCAR® Heat 2002" title. Originally will report as file not found on Windows but that is a bug. After attempt to correct the problem by use Windows' `SetConsole(Output)CP` functions. Cache file was not output properly due to C++20's filesystem's string are being treat as ansi string on Windows as well. Using u8string cast will make conversion to native string correctly.

Fix breakage when utf8 string was used in C++20's filesystem on Windows

---

src/OOVPADatabase/D3D8LTCG/3911.inl
src/OOVPADatabase/D3D8LTCG/4039.inl
src/OOVPADatabase/D3D8LTCG/4531.inl
src/OOVPADatabase/D3D8LTCG/4627.inl
src/OOVPADatabase/D3D8LTCG/4721.inl
src/OOVPADatabase/D3D8LTCG/5788.inl
src/OOVPADatabase/D3D8LTCG_OOVPA.inl
src/test/libverify/D3D8.cpp

Unit test were crowded by these missing renamed symbols. They should be at least cover most of the LTCG titles. I am able to translate these renamed symbols according to Cxbx-Reloaded's documentations.

Rename D3D8LTCG symbols

---

src/test/main.cpp

Plus add thread id for every message outputs if using multi-threading mode.
Only thing left intact are new lines from std::cout which are needed to split sections of messages from a console/log.

Forward all std::cout messages to a function

---

src/lib/internal_functions.h
src/lib/libXbSymbolDatabase.c

fixed #178
It was brought up while doing the unit test process with Xbox Dashboard (b5659) which end up showing:
```
Library[4]
name    = D3D8;
build   = 5659;
qre ver = 0x1;
flag    = 0x1;
Library[5]
name    = D3D8LTCG;
build   = 5659;
qre ver = 0x1;
flag    = 0x2;
```
With this pull request, now it is showing correctly for specific D3D8(LTCG) library to scan.
```
[00005a28] INFO   : Getting library and section filters...
[00005a28] INFO   : Outputting library filters...
[00005a28] INFO   : Library[0]
[00005a28] INFO   :     name    = XAPILIB
[00005a28] INFO   :     build   = 5659
[00005a28] INFO   :     qre ver = 0x1
[00005a28] INFO   :     flag    = 0x40
[00005a28] INFO   : Library[1]
[00005a28] INFO   :     name    = D3DX8
[00005a28] INFO   :     build   = 5659
[00005a28] INFO   : …
```

Fix XbSymbolDatabase_GenerateLibraryFilter for duplicate D3D8(LTCG) libraries

---

src/lib/libXbSymbolDatabase.c

When start testing Xbox dashboard with Cxbx-Reloaded to sync changes. It produced unintentional exception behavior from DSOUND section. It turns out DSOUND symbols were absent due to constant overridden by D3D8(LTCG) library boolean check. This pull request resolve regression by check active library check first then boolean check for duplicate flag.
fixed #179 regression

HOTFIX: Fix library filter generator

---

projects/UnitTest/CMakeLists.txt

According to recent active pull request's log. CMake expected minimal required to be 3.5 or above from external library used for unit test tool.
> CMake Deprecation Error at build/projects/UnitTest/xxhash-src/cmake_unofficial/CMakeLists.txt:8 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of CMake.
Since upstream already include a fix for this. I proceed with update xxhash submodule to v0.8.2 plus one merged pull request commit relative to cmake fix warning deprecation (which is being treated as error by `-Werror=dev` flag).

Update xxhash submodule to v0.8.2 and one commit ahead for necessary cmake error fix

---

src/lib/libXbSymbolDatabase.c

After reviewing codebase, I believe I found the source of endless loop for when dependency flags are returned but never checked if any of them are matched. Instead of fix cli and unittest tools, I recommended to fix it internally to work as intentional design. This fixed certain Chihiro titles containing D3D8I library except absent of D3D8I signatures support.
fixed #197

HOTFIX: fix endless loop for dependency flag check is completed or not

---

.github/labeler.yml
.github/workflows/ci.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
projects/UnitTest/CMakeLists.txt
src/OOVPADatabase/OOVPA.h
src/test/main.cpp

Due to GitHub Actions made some regression along with latest macOS's architecture change. I have determined to have all the fixes in one pull request to ensure the GitHub Actions upgrade directly are working with new requirement changes.
GitHub Actions upgrade:
- actions/checkout@v4
- actions/upload-artifact@v4
- actions/download-artifact@v4
- actions/labeler@v5
The github-script action is added due to workflow's matrix doesn't really accept dynamic selection for specific builder. Although, it does seem a little bloated but does the job simpler.
The previous upload method no longer works with upload-artifact v4. Which require additional job to merge all the upload artifacts into one after the matrix builders are done.
macOS latest (macos-14) made a change from x64 to amd64 architecture. …

Bulk misc updates

---

.github/workflows/ci.yml

I recently noticed my mistake of mixup with arm64 and amd64 wording. This hotfix pull request will compile with given architecture target on latest macOS image from Github CI. After inspection from GitHub CI log output, I can confirm they have been corrected.
references from this pull request's CI builds:
- ![image](https://github.com/Cxbx-Reloaded/XbSymbolDatabase/assets/3938312/f6528eb6-08be-4f1c-acb7-82d02939297d)
- ![image](https://github.com/Cxbx-Reloaded/XbSymbolDatabase/assets/3938312/d1a2bff5-e060-4385-8a75-237c0db5d5d9)
Technically, it could be possible to build universal binary bundled both x64 and arm64. However, Ghidra seems to use separate folder both architectures. For time being, we will have them build separately until there is a request to merge together.

HOTFIX: Fix arch typo and use latest macOS with target arch

---

.github/workflows/pull-request.yml

`DoozyX/clang-format-lint-action@v0.11` report an error, most likely GitHub's runner image may have changed over time.
```
Traceback (most recent call last):
File "/run-clang-format.py", line 25, in <module>
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

Update action to resolve missing distutils module error

---

include/libXbSymbolDatabase.h
src/cli/main.c
src/lib/internal_db_version.h
src/lib/internal_functions.h
src/lib/internal_tests.h
src/lib/libXbSymbolDatabase.c
src/lib/manual_custom.h
src/lib/manual_d3d8__ltcg.h
src/lib/manual_dsound.h
src/lib/manual_jvs.h
src/lib/manual_xapilib.h
src/test/libverify.cpp
src/test/main.cpp

close #78 
Changes were made to standardize the prefix of `XbSDB` for public APIs and `XbSDBi` for internal use only. The only prefix that does not have `XbSDBi` is `manual_` prefix functions.
I noticed some definitions that were not in full caps have also been updated. And missing static to one of the internal functions.

Rename APIs Prefix

---

src/OOVPADatabase/OOVPA.h
src/test/libverify/D3D8.cpp

One commit is forgotten to add to the #221 pull request with the unittest's symbol renamed.
The other commit is mainly to keep OOVPA signatures local only to OOVPA's group files. I am not entirely sure how this was missed duration of untangling from the manual scan process needs to access the OOVPA signatures directly. Relative to #218 pull request.

Minor fixes to unittest and future internal oovpa signatures conflict
